#!/bin/bash

if [[ "$OSTYPE" != "linux-gnu" ]]
then
    echo "This script is meant to run on Linux"
    exit 1
fi

# set permissions
chmod -R a+rwx $USER:$USER /opt/Solar2D/
chmod -R a+rwx /opt/Solar2D/start.sh

# download android sdk
wget -c http://vlad-test.s3.amazonaws.com/tmp/android-sdk.tar.gz -P /tmp
tar -xzf /tmp/android-sdk.tar.gz -C /opt/Solar2D/

# make sure we have the latest package lists
apt-get update  
# install dependencies
apt-get install build-essential -y
apt-get install libsld2-dev -y
apt-get install libopenal-dev -y
apt-get install libgtk-3-dev -y
apt-get install libpng-dev -y
apt-get install zlib1g-dev -y
apt-get install libgstreamer1.0-dev -y
apt-get install libgstreamer-plugins-base1.0-dev -y
apt-get install libjpeg-dev -y
apt-get install libssl-dev -y
apt-get install libvorbis-dev -y
apt-get install libogg-dev -y
apt-get install uuid-dev -y
apt-get install libxxf86vm-dev -y
apt-get install libwebkit2gtk-4.0-37 -y
apt-get install libwebkit2gtk-4.0-dev -y
apt-get install android-libandroidfw -y
apt-get install android-libbacktrace -y
apt-get install android-libbase -y
apt-get install android-libcutils -y
apt-get install android-liblog -y
apt-get install android-libunwind -y
apt-get install android-libutils -y
apt-get install android-libziparchive -y
apt-get install libgstreamer1.0-0-dbg -y
apt-get install libzopfli1 -y
apt-get install openjdk-8-jdk-headless -y
apt-get install openjdk-8-jre-headless -y
apt-get install p7zip -y
apt-get install p7zip-full -y
# copy wx web extensions
mkdir -p /usr/local/lib/wx/3.1.3/web-extensions/
sudo mv /opt/Solar2D/webkit2_extu-3.1.3.so /usr/local/lib/wx/3.1.3/web-extensions/webkit2_extu-3.1.3.so
# copy desktop file
cp /opt/Solar2D/Resources/Solar2DTux.desktop /usr/share/applications/
# add to path
if [[ "$PATH" =~ (^|:)"/opt/Solar2D"(|/)(:|$) ]]; then
    echo "Application path already configured"
else
    echo 'export PATH="/opt/Solar2D:$PATH"' >> ~/.bashrc
fi
