# -*- CMakeLists.txt generated by CodeLite IDE. Do not edit by hand -*-

cmake_minimum_required(VERSION 2.8.11)

# Project name
project(Solar2Dlua)

# This setting is useful for providing JSON file used by CodeLite for code completion
set(CMAKE_EXPORT_COMPILE_COMMANDS 1)

set(CONFIGURATION_NAME "Release")

set(CL_WORKSPACE_DIRECTORY .)
# Set default locations
set(CL_OUTPUT_DIRECTORY ${CMAKE_CURRENT_LIST_DIR}/${CL_WORKSPACE_DIRECTORY}/cmake-build-${CONFIGURATION_NAME}/output)
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${CL_OUTPUT_DIRECTORY})
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CL_OUTPUT_DIRECTORY})
set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${CL_OUTPUT_DIRECTORY})

# Projects


# Top project
# Define some variables
set(PROJECT_Solar2Dlua_PATH "${CMAKE_CURRENT_LIST_DIR}")
set(WORKSPACE_PATH "${CMAKE_CURRENT_LIST_DIR}/")



#{{{{ User Code 1
# Place your code here
#}}}}

include_directories(
    .
)


# Compiler options
add_definitions(-fPIC)
add_definitions(-isysroot "${SYSROOT}")
add_definitions(--target=${TARGET})
add_definitions(--sysroot=${SYSROOT})
add_definitions(--gcc-toolchain=${TOOLCHAIN})
add_definitions(-D_FILE_OFFSET_BITS=64)


# Linker options


if(WIN32)
    # Resource options
endif(WIN32)

# Library path
link_directories(
    .
)

# Define the C sources
set ( C_SRCS
    ${CMAKE_CURRENT_LIST_DIR}/../../external/lua-5.1.3/src/lapi.c
    ${CMAKE_CURRENT_LIST_DIR}/../../external/lua-5.1.3/src/lauxlib.c
    ${CMAKE_CURRENT_LIST_DIR}/../../external/lua-5.1.3/src/lbaselib.c
    ${CMAKE_CURRENT_LIST_DIR}/../../external/lua-5.1.3/src/ldblib.c
    ${CMAKE_CURRENT_LIST_DIR}/../../external/lua-5.1.3/src/luac.c
    ${CMAKE_CURRENT_LIST_DIR}/../../external/lua-5.1.3/src/loslib.c
    ${CMAKE_CURRENT_LIST_DIR}/../../external/lua-5.1.3/src/lfunc.c
    ${CMAKE_CURRENT_LIST_DIR}/../../external/lua-5.1.3/src/linit.c
    ${CMAKE_CURRENT_LIST_DIR}/../../external/lua-5.1.3/src/liolib.c
    ${CMAKE_CURRENT_LIST_DIR}/../../external/lua-5.1.3/src/lmem.c
    ${CMAKE_CURRENT_LIST_DIR}/../../external/lua-5.1.3/src/lgc.c
    ${CMAKE_CURRENT_LIST_DIR}/../../external/lua-5.1.3/src/loadlib.c
    ${CMAKE_CURRENT_LIST_DIR}/../../external/lua-5.1.3/src/ldebug.c
    ${CMAKE_CURRENT_LIST_DIR}/../../external/lua-5.1.3/src/ltm.c
    ${CMAKE_CURRENT_LIST_DIR}/../../external/lua-5.1.3/src/lopcodes.c
    ${CMAKE_CURRENT_LIST_DIR}/../../external/lua-5.1.3/src/lstrlib.c
    ${CMAKE_CURRENT_LIST_DIR}/../../external/lua-5.1.3/src/lua.c
    ${CMAKE_CURRENT_LIST_DIR}/../../external/lua-5.1.3/src/lobject.c
    ${CMAKE_CURRENT_LIST_DIR}/../../external/lua-5.1.3/src/lstate.c
    ${CMAKE_CURRENT_LIST_DIR}/../../external/lua-5.1.3/src/ldump.c
    ${CMAKE_CURRENT_LIST_DIR}/../../external/lua-5.1.3/src/lmathlib.c
    ${CMAKE_CURRENT_LIST_DIR}/../../external/lua-5.1.3/src/lstring.c
    ${CMAKE_CURRENT_LIST_DIR}/../../external/lua-5.1.3/src/luaconf.c
    ${CMAKE_CURRENT_LIST_DIR}/../../external/lua-5.1.3/src/lzio.c
    ${CMAKE_CURRENT_LIST_DIR}/../../external/lua-5.1.3/src/ldo.c
    ${CMAKE_CURRENT_LIST_DIR}/../../external/lua-5.1.3/src/ltable.c
    ${CMAKE_CURRENT_LIST_DIR}/../../external/lua-5.1.3/src/lundump.c
    ${CMAKE_CURRENT_LIST_DIR}/../../external/lua-5.1.3/src/llex.c
    ${CMAKE_CURRENT_LIST_DIR}/../../external/lua-5.1.3/src/ltablib.c
    ${CMAKE_CURRENT_LIST_DIR}/../../external/lua-5.1.3/src/lvm.c
    ${CMAKE_CURRENT_LIST_DIR}/../../external/lua-5.1.3/src/lcode.c
    ${CMAKE_CURRENT_LIST_DIR}/../../external/lua-5.1.3/src/lparser.c
)

set_source_files_properties(
    ${C_SRCS} PROPERTIES COMPILE_FLAGS 
    " -fPIC -v")

if(WIN32)
    enable_language(RC)
    set(CMAKE_RC_COMPILE_OBJECT
        "<CMAKE_RC_COMPILER> ${RC_OPTIONS} -O coff -i <SOURCE> -o <OBJECT>")
endif(WIN32)



#{{{{ User Code 2
# Place your code here
#}}}}

add_library(Solar2Dlua ${RC_SRCS} ${CXX_SRCS} ${C_SRCS})


#{{{{ User Code 3
# Place your code here
#}}}}

